// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	GetUserOrdersByName(ctx context.Context, name string) ([]*GetUserOrdersByNameRow, error)
	OrderCreateByUser(ctx context.Context, name string) error
	OrderDelete(ctx context.Context, id int) error
	OrderProductCreateByUserAndProductQuanti(ctx context.Context, arg OrderProductCreateByUserAndProductQuantiParams) error
	OrderProductsCreate(ctx context.Context, arg OrderProductsCreateParams) (pgconn.CommandTag, error)
	OrderUpdate(ctx context.Context, orderID int32) error
	OrderUpdateTotalAmountByOrderID(ctx context.Context, orderID int32) error
	Orders(ctx context.Context) ([]*ShopOrder, error)
	OrdersCreate(ctx context.Context, userID *int32) (pgconn.CommandTag, error)
	OrdersProducts(ctx context.Context) ([]*ShopOrderproduct, error)
	ProductCreate(ctx context.Context, arg ProductCreateParams) (int, error)
	ProductDelete(ctx context.Context, name string) error
	ProductGetById(ctx context.Context, id int) (*ShopProduct, error)
	ProductGetByName(ctx context.Context, name string) (*ShopProduct, error)
	ProductGetRangePrice(ctx context.Context, arg ProductGetRangePriceParams) ([]*ShopProduct, error)
	ProductUpdate(ctx context.Context, arg ProductUpdateParams) error
	Products(ctx context.Context) ([]*ShopProduct, error)
	UserAdd(ctx context.Context, arg UserAddParams) (int, error)
	UserByID(ctx context.Context, id int) (*ShopUser, error)
	UserDelete(ctx context.Context, name string) error
	UserGetByName(ctx context.Context, name string) (*ShopUser, error)
	UserUpdate(ctx context.Context, arg UserUpdateParams) error
	Users(ctx context.Context) ([]*ShopUser, error)
	UsersSumTotalOrdersAvrPrice(ctx context.Context) ([]*UsersSumTotalOrdersAvrPriceRow, error)
}

var _ Querier = (*Queries)(nil)
