// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"
)

type Querier interface {
	GetUserOrdersByName(ctx context.Context, name string) ([]*GetUserOrdersByNameRow, error)
	OrderByID(ctx context.Context, id int) (*ShopOrder, error)
	OrderCreateByUser(ctx context.Context, name string) (int, error)
	OrderDelete(ctx context.Context, id int) error
	OrderProductUpdate(ctx context.Context, arg OrderProductUpdateParams) error
	OrderProductsCreate(ctx context.Context, arg OrderProductsCreateParams) error
	OrderUpdateTotal(ctx context.Context, orderID int32) error
	OrderUser(ctx context.Context, id int) (*OrderUserRow, error)
	Orders(ctx context.Context) ([]*OrdersRow, error)
	OrdersProductsFull(ctx context.Context) ([]*OrdersProductsFullRow, error)
	ProductAddOrder(ctx context.Context, arg ProductAddOrderParams) error
	ProductCreate(ctx context.Context, arg ProductCreateParams) (int, error)
	ProductDelete(ctx context.Context, name string) error
	ProductGetById(ctx context.Context, id int) (*ShopProduct, error)
	ProductGetByName(ctx context.Context, name string) (*ShopProduct, error)
	ProductGetRangePrice(ctx context.Context, arg ProductGetRangePriceParams) ([]*ShopProduct, error)
	ProductID(ctx context.Context, name string) (int, error)
	ProductUpdate(ctx context.Context, arg ProductUpdateParams) error
	Products(ctx context.Context) ([]*ShopProduct, error)
	UserAdd(ctx context.Context, arg UserAddParams) (int, error)
	UserByID(ctx context.Context, id int) (*ShopUser, error)
	UserDelete(ctx context.Context, name string) error
	UserGetByName(ctx context.Context, name string) (*ShopUser, error)
	UserUpdate(ctx context.Context, arg UserUpdateParams) error
	Users(ctx context.Context) ([]*ShopUser, error)
	UsersStatistic(ctx context.Context) ([]*UsersStatisticRow, error)
}

var _ Querier = (*Queries)(nil)
