// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queryOderProducts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const OrderProductsCreate = `-- name: OrderProductsCreate :execresult
insert into shop.orderproducts 
(order_id, product_id, quantity)
values ($1, $2, $3)
`

type OrderProductsCreateParams struct {
	OrderID   int32          `db:"order_id" json:"order_id"`
	ProductID int32          `db:"product_id" json:"product_id"`
	Quantity  pgtype.Numeric `db:"quantity" json:"quantity"`
}

func (q *Queries) OrderProductsCreate(ctx context.Context, arg OrderProductsCreateParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, OrderProductsCreate, arg.OrderID, arg.ProductID, arg.Quantity)
}

const OrdersProducts = `-- name: OrdersProducts :many
select order_id, product_id, quantity from shop.orderproducts op
`

func (q *Queries) OrdersProducts(ctx context.Context) ([]*ShopOrderproduct, error) {
	rows, err := q.db.Query(ctx, OrdersProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ShopOrderproduct{}
	for rows.Next() {
		var i ShopOrderproduct
		if err := rows.Scan(&i.OrderID, &i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ProductAddOrder = `-- name: ProductAddOrder :exec
insert into shop.Orderproducts 
(order_id, product_id, quantity)
values 
( 
    $1, 
    (select id from shop.products p where p.name = $2),
    $3
)
`

type ProductAddOrderParams struct {
	OrderID  int32          `db:"order_id" json:"order_id"`
	Name     string         `db:"name" json:"name"`
	Quantity pgtype.Numeric `db:"quantity" json:"quantity"`
}

func (q *Queries) ProductAddOrder(ctx context.Context, arg ProductAddOrderParams) error {
	_, err := q.db.Exec(ctx, ProductAddOrder, arg.OrderID, arg.Name, arg.Quantity)
	return err
}
