// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const OrderCreate = `-- name: OrderCreate :exec
insert into shop.orderproducts 
(order_id, product_id, quantity)
values ($1, $2, $3)
`

type OrderCreateParams struct {
	OrderID   int32          `db:"order_id" json:"order_id"`
	ProductID int32          `db:"product_id" json:"product_id"`
	Quantity  pgtype.Numeric `db:"quantity" json:"quantity"`
}

func (q *Queries) OrderCreate(ctx context.Context, arg OrderCreateParams) error {
	_, err := q.db.Exec(ctx, OrderCreate, arg.OrderID, arg.ProductID, arg.Quantity)
	return err
}

const OrderProductsCreate = `-- name: OrderProductsCreate :execresult
insert into shop.orderproducts 
(order_id, product_id, quantity)
values ($1, $2, $3)
`

type OrderProductsCreateParams struct {
	OrderID   int32          `db:"order_id" json:"order_id"`
	ProductID int32          `db:"product_id" json:"product_id"`
	Quantity  pgtype.Numeric `db:"quantity" json:"quantity"`
}

func (q *Queries) OrderProductsCreate(ctx context.Context, arg OrderProductsCreateParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, OrderProductsCreate, arg.OrderID, arg.ProductID, arg.Quantity)
}

const OrderUpdate = `-- name: OrderUpdate :exec
update shop.orders ord
set total_amount=(
select sum(p.price * op.quantity) from 
shop.orderproducts op
inner join shop.products p on op.product_id=p.id
where op.order_id = $1
group by op.order_id)
where ord.id  = $1
`

func (q *Queries) OrderUpdate(ctx context.Context, orderID int32) error {
	_, err := q.db.Exec(ctx, OrderUpdate, orderID)
	return err
}

const OrdersCreate = `-- name: OrdersCreate :execresult
insert into shop.Orders(user_id)
values ($1)
`

func (q *Queries) OrdersCreate(ctx context.Context, userID *int32) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, OrdersCreate, userID)
}

const ProductCreate = `-- name: ProductCreate :execresult
insert into shop.Products(name, price)
values ($1, $2)
`

type ProductCreateParams struct {
	Name  string         `db:"name" json:"name"`
	Price pgtype.Numeric `db:"price" json:"price"`
}

func (q *Queries) ProductCreate(ctx context.Context, arg ProductCreateParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, ProductCreate, arg.Name, arg.Price)
}

const UserAdd = `-- name: UserAdd :execresult
insert into shop.Users(name, email, "password") 
values ($1, $2, $3)
`

type UserAddParams struct {
	Name     string  `db:"name" json:"name"`
	Email    *string `db:"email" json:"email"`
	Password string  `db:"password" json:"password"`
}

func (q *Queries) UserAdd(ctx context.Context, arg UserAddParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, UserAdd, arg.Name, arg.Email, arg.Password)
}

const Users = `-- name: Users :many





















select id, name, email, password from shop.users u
`

// update shop.orders ord
// set total_amount=(
// select sum(p.price * op.quantity) from
// shop.orderproducts op
// inner join shop.products p on op.product_id=p.id
// where op.order_id = 2
// group by op.order_id)
// where ord.id  = 2;
// insert into shop.Orders (user_id)
// values
// ((select id from shop.Users where name like 'qwe')
// );
// insert into shop.Orderproducts
// (order_id, product_id, quantity)
// values
// (
//
//	(select id from shop.orders
//	where user_id = (select id from shop.Users where name like 'qwe')),
//	(select id from shop.products
//
// where name like 'milk'), 2),
// (
//
//	(select id from shop.orders
//	where user_id = (select id from shop.Users where name like 'qwe')),
//	(select id from shop.products
//	where name like 'bread'), 2);
//
// update shop.orders ord
// set total_amount=(
//
//	select sum(p.price * op.quantity) from
//	shop.orderproducts op
//	inner join shop.products p on op.product_id=p.id
//	where op.order_id = 3
//	group by op.order_id)
//
// where ord.id = 3;
// insert into shop.orderproducts
// (order_id, product_id, quantity)
// values
// (2, 2, 2),
// (2, 1, 0.3);
// insert into shop.Orders (user_id)
// values
// ((select id from shop.Users where name like 'admi%')),
// ((select id from shop.Users where name like 'admi%'));
// insert into shop.Orderproducts
// (order_id, product_id, quantity)
// values
// (4, (select id from shop.products where name like 'potat%'), 4.76),
// (4, (select id from shop.products where name like 'butter'), 0.8);
// insert into shop.Orderproducts
// (order_id, product_id, quantity)
// values
// (5, (select id from shop.products where name like 'milk'), 1);
// update shop.orders ord
// set total_amount=(
//
//	select sum(p.price * op.quantity) from
//	shop.orderproducts op
//	inner join shop.products p on op.product_id=p.id
//	where op.order_id = 4
//	group by op.order_id)
//
// where ord.id = 4;
// update shop.orders ord
// set total_amount=(
//
//	select sum(p.price * op.quantity) from
//	shop.orderproducts op
//	inner join shop.products p on op.product_id=p.id
//	where op.order_id = 5
//	group by op.order_id)
//
// where ord.id = 5;
// --========================
// --update data (users, products)
// update shop.users
// set name = 'user'
// where "name" like 'as%';
// update shop.products
// set price = 102.2
// where name like 'mil%';
// --========================================
// --delete data (users, products, orders)
// DELETE from shop.Users
// where name='qwe';
// delete from shop.products
// where name like 'milk';
// update shop.orders ord
// set total_amount=(
// select sum(p.price * op.quantity) from
// shop.orderproducts op
// inner join shop.products p on op.product_id=p.id
// where op.order_id = 1
// group by op.order_id);
// delete from shop.orders
// where id=2;
// --========================================
// --Напишите запрос на выборку пользователей и выборку товаров
// --Напишите запрос на выборку заказов по пользователю
// --Напишите запрос на выборку статистики по пользователю (общая сумма заказов/средняя цена товара)
func (q *Queries) Users(ctx context.Context) ([]*ShopUser, error) {
	rows, err := q.db.Query(ctx, Users)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ShopUser{}
	for rows.Next() {
		var i ShopUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
