// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ShopOrder struct {
	ID          int                `db:"id" json:"id"`
	UserID      int32              `db:"user_id" json:"user_id"`
	OrderDate   pgtype.Timestamptz `db:"order_date" json:"order_date"`
	TotalAmount pgtype.Numeric     `db:"total_amount" json:"total_amount"`
}

type ShopOrderproduct struct {
	OrderID   int32          `db:"order_id" json:"order_id"`
	ProductID int32          `db:"product_id" json:"product_id"`
	Quantity  pgtype.Numeric `db:"quantity" json:"quantity"`
}

type ShopProduct struct {
	ID    int            `db:"id" json:"id"`
	Name  string         `db:"name" json:"name"`
	Price pgtype.Numeric `db:"price" json:"price"`
}

type ShopUser struct {
	ID       int     `db:"id" json:"id"`
	Name     string  `db:"name" json:"name"`
	Email    *string `db:"email" json:"email"`
	Password string  `db:"password" json:"password"`
}
