definitions:
  repository.UserAddParams:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
host: 0.0.0.0:8080/
info:
  contact: {}
  description: API Server
  title: 'HW15: shop'
  version: "1"
paths:
  /add_user:
    post:
      consumes:
      - application/json
      parameters:
      - description: Модель которую принимает метод
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/repository.UserAddParams'
      produces:
      - application/json
      responses:
        "200":
          description: Added user
          schema:
            type: string
        "400":
          description: Error
          schema:
            type: string
      summary: addUser
      tags:
      - addUser
  /user:
    get:
      consumes:
      - application/json
      parameters:
      - description: string valid
        in: query
        name: id
        type: string
      - description: string valid
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Get user by parameters
          schema:
            type: string
        "400":
          description: Error
          schema:
            type: string
      summary: get User by parameters
      tags:
      - getUserByParameters
  /users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Get users
          schema:
            type: string
        "400":
          description: Error
          schema:
            type: string
      summary: get users
      tags:
      - getUsers
swagger: "2.0"
