services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - pg

  pg:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ${APP_DB_DATABASE}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "${APP_DB_PORT}:5432"
